name: Docker Image CI

on:
  create:
  pull_request:
    branches:
      - master
  push:
    tags-ignore: 
      - '**'
    branches:
      - master
      - fork/master

jobs:
  build_pr:
    name: "Build PR Docker image"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [32, 64]
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile-${{ matrix.arch }}
    

  build_edge:
    name: "Build edge Docker image"
    if: github.event_name != 'create' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [32, 64]
    steps:
    - uses: actions/checkout@v1
    - name: Login to GitHub Docker Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u github-actions --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile-${{ matrix.arch }} --tag docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:edge
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:edge

  build_release:
    name: "Build release Docker image"
    if: github.event_name == 'create' && github.event.ref_type == 'tag' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch_bits: [32, 64]
    steps:
    - uses: actions/checkout@v1
    - name: Login to GitHub Docker Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u github-actions --password-stdin
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile-${{ matrix.arch }} --tag docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:latest
        docker tag docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:latest docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:${{ github.event.ref }}
    - name: Push the Docker image
      run: |
        docker push docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:latest
        docker push docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:${{ github.event.ref }}
