name: Docker Image CI

on:
  create:
  workflow_dispatch:
  schedule:
    - cron: '15 05 * * 1' # Late night for the Americas, early morning for Europe
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - master
  push:
    paths-ignore:
      - '**.md'
    tags-ignore:
      - '**'
    branches:
      - master
      - fork/master

jobs:
  code_check:
    name: Code checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -x

  build_pr:
    name: "Test Build Docker image"
    if: github.event_name == 'pull_request' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [32, 64]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile-${{ matrix.arch }} --build-arg DISABLE_OPTIMIZATIONS=1

  build_edge:
    name: "Build edge Docker image"
    if: github.event_name != 'create' && github.event_name != 'pull_request' && github.event_name != 'schedule'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [32, 64]
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Docker Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u github-actions --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile-${{ matrix.arch }} --build-arg DISABLE_OPTIMIZATIONS=1 --tag docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:edge
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:edge

  build_release:
    name: "Build release Docker image"
    if: github.event_name == 'create' && github.event.ref_type == 'tag' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch_bits: [32, 64]
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Docker Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u github-actions --password-stdin
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile-${{ matrix.arch }} --tag docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:latest
        docker tag docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:latest docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:${{ github.event.ref }}
    - name: Push the Docker image
      run: |
        docker push docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:latest
        docker push docker.pkg.github.com/phusion/holy-build-box/hbb-${{ matrix.arch }}:${{ github.event.ref }}
